version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres-assets
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net

  app:
    build: .
    container_name: asset-crud-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
    volumes:
      - .:/usr/src/app
    networks:
      - app-net

volumes:
  postgres_data:

networks:
  app-net:
    driver: bridge
