version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres-assets
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: assets_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-net

  backend:
    build: ./backend
    container_name: asset-crud-backend
    restart: always
    depends_on:
      - db
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: assets_db
      JWT_SECRET: supersecret
    ports:
      - "3000:3000"
    networks:
      - app-net

  frontend:
    build: ./frontend
    container_name: asset-crud-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-net

volumes:
  postgres_data:

networks:
  app-net:
    driver: bridge
